file = open('output.txt','w')
a=input("Enter text to write to the file: ")
result=file.write(a+'\n')
file.close()
print("Data successfully written to output.txt.")
file = open('output.txt','a')
b=input("Enter additional text to append: ")
output=file.write(b)
file.close()
print("Data successfully appended ")
print("Final content of output.txt: ")
file = open('output.txt','r')
readlines = file.read()
print(readlines)
